### ISSUE TITLE
Invalid Relationship Errors

### ISSUE THREAD

**Issue by gma1083** [cucucachu/noomman#14]
Update the ClassModel.finalize() method to catch two-way relationships that are not set up properly.

In the diffable logic, check for improperly set up relationships and throw better errors.

**Comment by cucucachu** [comment]
Two helper methods ClassModel.getRelationship() and ClassModel.getRelatedClassModel() now have better error handling. These methods are now used in ClassModel.cardinalityOfRelationship() which was the cause of most of the relationship errors. This method now calls those other methods and checks for null or undefined respectively, to throw more helpful errors before continuing with execution. 

Updated comments on those methods.

Also updated finalize to call those methods for better error handling.
