### ISSUE TITLE
Walking Multiple Relationships

### ISSUE THREAD

**Issue by cucucachu** [cucucachu/noomman#15]
Implement a new syntax for walking multiple relationships, without having to string together multiple await statements. 

Currently, to walk multiple relationships, a developer must do something like the following:
await (await (await instanceA.relationshipToB).relationshipToC).relationshipToD

This syntax is difficult to read and hard to debug. Instead, add a new method walkPath() to Instance and InstanceSet. 
await instanceA.walkPath(['relationshipB', 'relationshipC', 'relationshipD');

walkPath should: 
- throw  an error if path is invalid
- return an InstanceSet containing all Instances that result from walking the path.
- If no instances result from walking the path, then an empty InstanceSet is returned with 
   the ClassModel that results from walking the complete path.

Also add a get trap condition so that a user can call walk path with the following syntax:
await instanceA['->relationshipB->relationshipC->relationshipD'];

In the get trap, we will look for a preceding '->' , parse out each relationship, and do all the walking, and then call walkPath.

**Comment by gma1083** [comment]
Dopeeeee

**Comment by cucucachu** [comment]
Wrote new methods Instance.walkPath() and InstanceSet.walkPath().

Wrote new get trap which calls Instance.walkPath() when property is preceded by "->".

Wrote new supporting methods ClassModel.validatePath() and Instance.parsePath(). 

Wrote new misc. method InstanceSet.instanceAt(index), which returns the instance at the given index as though the InstanceSet were an array.

Tested all new methods and get trap, added comments, and updated html documentation for those that are exposed to the user.
