### ISSUE TITLE
Make Relationship Id(s) Accessible

### ISSUE THREAD

**Issue by cucucachu** [cucucachu/noomman#16]
For testing purposes it is often easier to compare the id or ids values of a relationship without actually walking the relationship.

Implement a new syntax using a get trap on Instance so that a user can grab the id or array of ids that the relationship is set to.

for a singular relationship:
instance.singularRelationship_id should return the id that the relationship is set to, or null.

for non-singular relationships: 
instance.nonSingularRelationship_ids should return an array of ids that the relationship is set to, or empty array.

**Comment by gma1083** [comment]
Sweet

**Comment by cucucachu** [comment]
Users can now access the id or ids held in a relationship by using the following syntax for an instance called instance and a relationship called relationship.
instance.relationship_id returns the id of the related instance for a singular relationship.
instance.relationship_ids returns the ids of the related instances as an array for a non-singular relationship.

Added new tests in InstanceTests.js

No documentation or comments.
